# Generated by Django 4.2.17 on 2024-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='enterprise_or_government',
            field=models.CharField(choices=[('Enterprise', 'Enterprise'), ('Government', 'Government')], default='1', max_length=20),
            preserve_default=False,
        ),
    ]
